[package]
name = "abap-lsp"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "abap-language-server"
path = "src/main.rs"

[dependencies]
tower-lsp-server = "0.23.0"
tokio = { version = "1.47.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_yaml_ng = "0.10"
thiserror = "2.0"
toml = "0.9"
url = "2.5"
zadt = { path = "../ziege/crates/zadt", features = ["reqwest"] }
zaff = { path = "../ziege/crates/zaff" }
zvfs = { path = "../ziege/crates/zvfs" }

[dev-dependencies]
tempfile = "3.20"
